"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ClipboardCheck, Copy, Loader2, Plus, ShieldCheck } from "lucide-react";
import { Shell } from "@/components/dashboard/shell";

type Summary = { records: number; scheduled_reminders: number; open_customer_requests: number; live_messages_enabled: boolean; release_status: string };
type RecordItem = { id: number; customer_name: string; job_title: string; completed_on: string; next_service_on: string | null; status: string };
type CustomerAction = { id: number; action_type: string; note: string | null; created_at: string; customer_name: string; job_title: string };

const initial = { contractor_name: "", contractor_phone: "", contractor_email: "", customer_name: "", customer_phone: "", customer_email: "", service_address: "", job_title: "", job_summary: "", completed_on: new Date().toISOString().slice(0, 10), invoice_reference: "", warranty_summary: "", warranty_expires_on: "", maintenance_instructions: "", next_service_on: "", customer_consented_to_reminders: false };

export default function NeverForgetPage() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [records, setRecords] = useState<RecordItem[]>([]);
  const [actions, setActions] = useState<CustomerAction[]>([]);
  const [form, setForm] = useState(initial);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [recordUrl, setRecordUrl] = useState<string | null>(null);
  const load = useCallback(async () => { const [s, r, a] = await Promise.all([fetch("/api/never-forget/summary", { cache: "no-store" }), fetch("/api/never-forget/records", { cache: "no-store" }), fetch("/api/never-forget/actions", { cache: "no-store" })]); if (s.ok) setSummary(await s.json()); if (r.ok) setRecords((await r.json()).items); if (a.ok) setActions((await a.json()).items); }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); const body = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value === "" ? null : value])); const response = await fetch("/api/never-forget/records", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setMessage(payload.detail?.[0]?.msg || payload.detail || "The record could not be saved"); return; } setRecordUrl(payload.customer_record_url); setMessage("Service record created. No message was sent automatically."); setForm(initial); setShowForm(false); await load(); }
  return <Shell><div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Customer retention</p><h1 className="mt-1 text-2xl font-semibold text-white">Never Forget</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Give customers one clear service record with warranty details, maintenance instructions and the next service date.</p></div><button onClick={() => setShowForm(value => !value)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Plus className="h-4 w-4" />New service record</button></div>
  <div className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm text-amber-100"><ShieldCheck className="mr-2 inline h-4 w-4" />Controlled MVP. Customer messages are disabled until consent and delivery acceptance testing is approved.</div>
  <div className="grid gap-3 sm:grid-cols-4">{[["Service records", summary?.records ?? 0], ["Scheduled reminders", summary?.scheduled_reminders ?? 0], ["Customer requests", summary?.open_customer_requests ?? 0], ["Live messages", summary?.live_messages_enabled ? "Enabled" : "Off"]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</div>
  {message && <div className="rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-slate-200">{message}</div>}{recordUrl && <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4"><p className="font-medium text-emerald-200">Private customer link</p><div className="mt-2 flex gap-2"><input readOnly value={recordUrl} className="min-w-0 flex-1 rounded-lg bg-slate-950 px-3 py-2 text-sm text-slate-300" /><button onClick={() => void navigator.clipboard.writeText(recordUrl)} className="rounded-lg border border-white/10 px-3 text-slate-200" aria-label="Copy private link"><Copy className="h-4 w-4" /></button></div></div>}
  {showForm && <form onSubmit={submit} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="text-lg font-semibold text-white">Create the customer record</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[["contractor_name", "Business name", true], ["contractor_phone", "Business phone", false], ["contractor_email", "Business email", false], ["customer_name", "Customer name", true], ["customer_phone", "Customer phone", false], ["customer_email", "Customer email", false], ["service_address", "Service address", false], ["job_title", "Work completed", true], ["completed_on", "Completed date", true], ["invoice_reference", "Invoice reference", false], ["warranty_expires_on", "Warranty expiry", false], ["next_service_on", "Next service date", false]].map(([key, label, required]) => <label key={String(key)} className="text-sm text-slate-300"><span>{label}</span><input type={String(key).includes("_on") ? "date" : "text"} required={Boolean(required)} value={String(form[key as keyof typeof form] ?? "")} onChange={event => setForm({ ...form, [String(key)]: event.target.value })} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2.5 text-white" /></label>)}</div>{[["job_summary", "What was done"], ["warranty_summary", "Warranty information"], ["maintenance_instructions", "Maintenance instructions"]].map(([key, label]) => <label key={key} className="mt-3 block text-sm text-slate-300"><span>{label}</span><textarea required={key === "job_summary"} value={String(form[key as keyof typeof form])} onChange={event => setForm({ ...form, [key]: event.target.value })} rows={3} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2.5 text-white" /></label>)}<label className="mt-4 flex items-start gap-3 text-sm text-slate-300"><input type="checkbox" checked={form.customer_consented_to_reminders} onChange={event => setForm({ ...form, customer_consented_to_reminders: event.target.checked })} className="mt-1" /><span>The customer explicitly agreed to receive service reminders. This records consent but does not send a message while the MVP switch is off.</span></label><button disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-2.5 font-semibold text-slate-950 disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <ClipboardCheck className="h-4 w-4" />}Create private record</button></form>}
  {actions.length > 0 && <section><h2 className="text-lg font-semibold text-white">Customer requests</h2><div className="mt-3 space-y-2">{actions.map(action => <div key={action.id} className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4"><p className="font-medium text-white">{action.customer_name} · {action.action_type.replaceAll("_", " ")}</p><p className="mt-1 text-sm text-slate-300">{action.note || `Regarding ${action.job_title}`}</p><p className="mt-2 text-xs text-slate-500">{new Date(action.created_at).toLocaleString()}</p></div>)}</div></section>}
  <section><h2 className="text-lg font-semibold text-white">Recent service records</h2><div className="mt-3 space-y-2">{records.length === 0 ? <div className="rounded-xl border border-white/10 bg-white/5 p-8 text-center text-sm text-slate-400">No service records yet.</div> : records.map(record => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/5 p-4"><div><p className="font-medium text-white">{record.customer_name}</p><p className="text-sm text-slate-400">{record.job_title} · completed {record.completed_on}</p></div><p className="text-xs text-slate-400">{record.next_service_on ? `Next service ${record.next_service_on}` : "No reminder scheduled"}</p></div>)}</div></section></div></Shell>;
}
