"""Evidence based starter portfolio for the App Factory.

Scores are commercial hypotheses, not claims. Only candidates with three independent
sources may move from research to validation. A score never authorizes production.
"""

SCORE_WEIGHTS = {
    "pain_severity": 15,
    "frequency": 10,
    "willingness_to_pay": 15,
    "ease_of_distribution": 15,
    "low_onboarding": 10,
    "low_operating_cost": 10,
    "development_feasibility": 10,
    "differentiation": 5,
    "retention": 5,
    "pns_reuse": 5,
}


def _candidate(
    slug: str,
    name: str,
    audience: str,
    problem: str,
    product_format: str,
    price: str,
    distribution: str,
    workaround: str,
    scores: list[int],
    reason: str,
    cost: int = 1500,
    risk: str = "low",
) -> dict:
    score = dict(zip(SCORE_WEIGHTS, scores, strict=True))
    return {
        "slug": slug,
        "name": name,
        "audience": audience,
        "problem": problem,
        "proposed_format": product_format,
        "proposed_price": price,
        "distribution_thesis": distribution,
        "current_workaround": workaround,
        "score": score,
        "total_score": sum(score.values()),
        "decision": "research",
        "decision_reason": reason,
        "estimated_monthly_cost_cents": cost,
        "risk_level": risk,
    }


CANDIDATES = [
    _candidate(
        "never-forget",
        "Never Forget",
        "Small service businesses and their customers",
        "After a job, receipts, warranties, photos and future maintenance are scattered or forgotten.",
        "SMS service plus lightweight web record",
        "$29, $79 or $149 monthly",
        "Existing PNS contractor relationships, search pages, trade associations and referrals",
        "Paper, camera roll, email, spreadsheets and memory",
        [14, 9, 13, 12, 10, 9, 9, 4, 5, 5],
        "Strong fit for a validation experiment. Product development remains blocked until purchase intent is measured.",
    ),
    _candidate(
        "phone-first-family-reminders",
        "Phone First Family Reminders",
        "Families supporting older adults who avoid apps",
        "Important reminders fail because the recipient does not reliably use smartphone apps or texts.",
        "Scheduled telephone service",
        "$12 household monthly",
        "Caregiver communities, senior centres and home care partners",
        "A family member calls repeatedly",
        [14, 9, 11, 10, 10, 8, 8, 4, 4, 5],
        "Validate willingness to pay and escalation safety before any build.",
        2500,
        "medium",
    ),
    _candidate(
        "home-record",
        "Simple Home Record",
        "Homeowners",
        "Receipts, warranties and maintenance dates are difficult to find when needed.",
        "Local first PWA",
        "$19 one time or $2 monthly sync",
        "Home maintenance search traffic, inspectors and contractors",
        "Binders, email search and spreadsheets",
        [12, 8, 8, 11, 9, 10, 9, 3, 4, 3],
        "Promising but must prove differentiation from existing home inventory apps.",
    ),
    _candidate(
        "missed-appointment-recovery",
        "Missed Appointment Recovery",
        "Independent non medical appointment businesses",
        "Late cancellations and missed appointments leave unused capacity.",
        "SMS service",
        "$39 monthly",
        "Scheduling consultants and local service search",
        "Manual reminder calls and calendar notes",
        [12, 8, 12, 10, 8, 8, 8, 3, 4, 5],
        "Potential validation candidate. Avoid health data and regulated clinics initially.",
        3000,
        "medium",
    ),
    _candidate(
        "trade-quote-followup",
        "Trade Quote Follow Up",
        "Small contractors",
        "Quotes are sent but follow up is inconsistent, so warm jobs go cold.",
        "CRM module plus SMS",
        "$29 monthly",
        "Never Miss users and contractor outreach",
        "Calendar reminders, notebooks and memory",
        [12, 9, 12, 10, 8, 8, 9, 2, 4, 5],
        "Useful adjacency, but competitor saturation may make this a Never Miss feature rather than a product.",
    ),
    _candidate(
        "renewal-vault",
        "Renewal Vault",
        "Households and microbusinesses",
        "Licences, insurance and document renewals are missed.",
        "Local first PWA",
        "$15 yearly",
        "Search, accountants, newcomer groups",
        "Calendar entries and paper folders",
        [11, 7, 8, 10, 9, 10, 9, 4, 4, 2],
        "Research whether a narrow Canadian segment has stronger pain.",
    ),
    _candidate(
        "home-emergency-card",
        "Home Emergency Card",
        "Homeowners and tenants",
        "People cannot quickly find shutoff, insurer and emergency instructions during a home incident.",
        "Offline PWA plus printable QR card",
        "$12 one time",
        "Inspectors, insurers, plumbers and search",
        "Paper notes and calling a family member",
        [12, 5, 7, 11, 10, 10, 9, 4, 2, 2],
        "Low cost candidate. Needs evidence of repeatable purchase intent.",
    ),
    _candidate(
        "document-expiry-reminder",
        "Document Expiry Reminder",
        "Canadian families and newcomers",
        "Passports, permits and certifications expire without enough preparation time.",
        "Local first PWA",
        "$15 yearly",
        "Settlement organizations and search",
        "Phone calendar and spreadsheets",
        [11, 6, 8, 10, 9, 10, 9, 3, 3, 2],
        "Keep away from legal advice and official status claims.",
    ),
    _candidate(
        "vehicle-proof-vault",
        "Vehicle Service Proof",
        "Vehicle owners and small fleets",
        "Maintenance proof and receipts are scattered when selling or claiming warranty.",
        "Local first PWA",
        "$19 one time",
        "Repair shops, used vehicle search and referrals",
        "Glovebox paper, email and photos",
        [10, 7, 7, 9, 9, 10, 9, 3, 3, 2],
        "Investigate repair shop funded distribution.",
    ),
    _candidate(
        "household-subscription-calendar",
        "Household Subscription Calendar",
        "Families avoiding bank connected apps",
        "Renewals and free trial end dates are forgotten.",
        "Local only PWA",
        "$9 one time",
        "Privacy focused search and app stores",
        "Calendar reminders and statements",
        [8, 8, 5, 9, 10, 10, 10, 2, 2, 1],
        "Crowded category with weak willingness to pay.",
    ),
    _candidate(
        "invoice-nudge",
        "Invoice Nudge",
        "Freelancers and microbusinesses",
        "Owners delay awkward invoice follow ups and harm cash flow.",
        "Email utility",
        "$9 monthly",
        "Freelancer communities and accounting partners",
        "Manual email and spreadsheets",
        [12, 9, 10, 8, 8, 8, 9, 1, 4, 3],
        "Real pain but heavily served. Reject unless a narrow underserved segment appears.",
    ),
    _candidate(
        "contractor-quote-check",
        "Contractor Quote Check",
        "Canadian homeowners",
        "Homeowners struggle to compare scopes and omissions across renovation quotes.",
        "Website tool",
        "$19 per comparison",
        "Renovation search and home inspectors",
        "Manual side by side review",
        [13, 5, 9, 11, 8, 7, 8, 1, 1, 2],
        "Direct Canadian competitors exist. Do not build without new differentiation.",
        3000,
        "medium",
    ),
    _candidate(
        "care-circle",
        "Care Circle",
        "Family caregivers",
        "Care tasks and updates are fragmented across family group chats.",
        "PWA",
        "$8 household monthly",
        "Caregiver communities and care providers",
        "Group chats, paper and shared calendars",
        [13, 9, 8, 8, 6, 7, 7, 1, 5, 2],
        "Crowded category and support burden are substantial.",
        4000,
        "medium",
    ),
    _candidate(
        "family-scam-escalation",
        "Family Scam Escalation",
        "Families supporting older adults",
        "A suspicious call or message is acted on before a trusted family member can help.",
        "Telephone and SMS service",
        "$10 household monthly",
        "Banks, senior organizations and family referrals",
        "Calling relatives after the fact",
        [15, 7, 9, 8, 8, 6, 6, 3, 4, 4],
        "High trust and liability risk. Research only.",
        5000,
        "high",
    ),
    _candidate(
        "hold-callback",
        "Call Me When It Is My Turn",
        "Consumers waiting on telephone hold",
        "People lose time listening to hold music.",
        "Android telephone utility",
        "$3 monthly",
        "App store search",
        "Speakerphone and waiting",
        [10, 6, 5, 9, 9, 6, 5, 3, 2, 3],
        "Carrier and platform behaviour create technical uncertainty.",
        4500,
        "medium",
    ),
    _candidate(
        "executor-organizer",
        "Executor Organizer",
        "Canadian estate executors",
        "First time executors struggle to track documents, tasks and institutions.",
        "Local desktop or PWA",
        "$49 one time",
        "Estate lawyers and search",
        "Binders, spreadsheets and legal checklists",
        [14, 3, 11, 9, 5, 8, 6, 1, 1, 1],
        "Legal sensitivity and established competitors make this unattractive now.",
        3000,
        "high",
    ),
    _candidate(
        "rental-listing-check",
        "Rental Listing Check",
        "Canadian renters",
        "Renters have difficulty recognizing fraudulent listings before sending money.",
        "Website tool",
        "$5 per check",
        "Search and tenant associations",
        "Reverse image search and manual checks",
        [14, 5, 4, 11, 9, 7, 6, 2, 1, 1],
        "False reassurance creates unacceptable liability without authoritative data.",
        3500,
        "high",
    ),
    _candidate(
        "private-budget",
        "Private Canadian Budget",
        "Canadians who avoid bank connections",
        "Many budgeting tools do not connect reliably to Canadian banks or require too much setup.",
        "Local first PWA",
        "$19 one time",
        "App store and privacy search",
        "Spreadsheets and manual exports",
        [9, 9, 6, 7, 7, 10, 8, 1, 3, 1],
        "Crowded market and migration burden reduce attractiveness.",
    ),
    _candidate(
        "immigration-deadline-tracker",
        "Immigration Deadline Tracker",
        "Canadian newcomers",
        "People track changing application tasks and deadlines across documents and portals.",
        "Local PWA",
        "$19 one time",
        "Settlement partners and search",
        "Spreadsheets, notes and forums",
        [13, 5, 8, 9, 6, 8, 6, 2, 1, 1],
        "Legal and policy change risk is too high for the current team.",
        3000,
        "high",
    ),
    _candidate(
        "medication-reminder",
        "Simple Medication Reminder",
        "Older adults and caregivers",
        "Medication routines are missed or duplicated.",
        "Android app",
        "$4 monthly",
        "App store and pharmacies",
        "Pill boxes, alarms and caregiver calls",
        [15, 10, 6, 6, 6, 7, 7, 1, 5, 1],
        "Medical harm risk and mature competitors make this a rejection.",
        3500,
        "high",
    ),
]


EVIDENCE = {
    "never-forget": [
        (
            "community",
            "Homeowners discuss losing warranty records",
            "https://www.reddit.com/r/homeowner/comments/1v6ivkh/how_do_you_keep_track_of_appliance_warranties/",
            "2026-08-18",
            "People report binders, spreadsheets and missed maintenance reminders.",
            "workaround",
        ),
        (
            "community",
            "Homeowners manage warranties and invoices manually",
            "https://www.reddit.com/r/homeowners/comments/1n0ahov/how_do_you_guys_manage_warranties_and_invoices/",
            "2026-08-18",
            "Users describe lost invoices and expired service benefits.",
            "pain",
        ),
        (
            "competitor",
            "House Fax home history platform",
            "https://myhousefax.ca/",
            "2026-08-18",
            "Existing spending validates the category while homeowner onboarding leaves room for a contractor funded approach.",
            "market",
        ),
    ],
    "phone-first-family-reminders": [
        (
            "community",
            "Caregiver built telephone reminders for a parent",
            "https://www.reddit.com/r/CaregiverSupport/comments/1puu34j/my_dad_struggles_with_smartphone_buttonsapps_so_i/",
            "2026-08-18",
            "A caregiver reports calling three or four times daily because apps and texts fail.",
            "workaround",
        ),
        (
            "report",
            "Statistics Canada home care needs report",
            "https://www150.statcan.gc.ca/n1/pub/82-570-x/82-570-x2024001-eng.pdf",
            "2026-08-18",
            "Canada has a large population receiving home care and reporting unmet support needs.",
            "market",
        ),
        (
            "report",
            "Maple Canadian caregiver survey",
            "https://www.getmaple.ca/newsroom/announcements/maple-report-only-15-percent-of-canadian-family-caregivers-say-the-health-care-system-meets-their-needs-all-the-time/",
            "2026-08-18",
            "Family caregivers report persistent coordination gaps.",
            "pain",
        ),
    ],
}
