from typing import Protocol

from app.domain.sales.entities import (
    ActivityCreate,
    ActivityListResponse,
    ActivityRead,
    ActivityUpdate,
    ContactCreate,
    ContactListResponse,
    ContactRead,
    ContactUpdate,
    OpportunityCreate,
    OpportunityListResponse,
    OpportunityRead,
    OpportunityUpdate,
    TaskCreate,
    TaskListResponse,
    TaskRead,
    TaskUpdate,
)


class ContactRepository(Protocol):
    def create(self, data: ContactCreate, organization_id: int) -> ContactRead: ...
    def list(self, *, organization_id: int, company_id: int, page: int, page_size: int, search: str | None) -> ContactListResponse: ...
    def get(self, contact_id: int, organization_id: int) -> ContactRead: ...
    def update(self, contact_id: int, data: ContactUpdate, organization_id: int) -> ContactRead: ...
    def delete(self, contact_id: int, organization_id: int) -> ContactRead: ...


class ActivityRepository(Protocol):
    def create(self, data: ActivityCreate, organization_id: int) -> ActivityRead: ...
    def list(self, *, organization_id: int, company_id: int | None, page: int, page_size: int, activity_type: str | None) -> ActivityListResponse: ...
    def get(self, activity_id: int, organization_id: int) -> ActivityRead: ...
    def update(self, activity_id: int, data: ActivityUpdate, organization_id: int) -> ActivityRead: ...


class TaskRepository(Protocol):
    def create(self, data: TaskCreate, organization_id: int) -> TaskRead: ...
    def list(self, *, organization_id: int, company_id: int | None, page: int, page_size: int, status: str | None, priority: str | None) -> TaskListResponse: ...
    def get(self, task_id: int, organization_id: int) -> TaskRead: ...
    def update(self, task_id: int, data: TaskUpdate, organization_id: int) -> TaskRead: ...


class OpportunityRepository(Protocol):
    def create(self, data: OpportunityCreate, organization_id: int) -> OpportunityRead: ...
    def list(self, *, organization_id: int, company_id: int | None, page: int, page_size: int, stage: str | None) -> OpportunityListResponse: ...
    def get(self, opportunity_id: int, organization_id: int) -> OpportunityRead: ...
    def update(self, opportunity_id: int, data: OpportunityUpdate, organization_id: int) -> OpportunityRead: ...
