import { notFound } from "next/navigation";
import { ServiceRecordActions } from "@/components/service-record-actions";

export const dynamic = "force-dynamic";

type ServiceRecord = { contractor_name: string; contractor_phone: string | null; contractor_email: string | null; customer_name: string; service_address: string | null; job_title: string; job_summary: string; completed_on: string; invoice_reference: string | null; receipt_url: string | null; work_photo_urls: string[]; warranty_summary: string | null; warranty_expires_on: string | null; maintenance_instructions: string | null; next_service_on: string | null };

export default async function ServiceRecordPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const api = process.env.NEXT_PUBLIC_API_BASE_URL || "https://api.pacificnorthsystems.com";
  const response = await fetch(`${api}/api/v1/never-forget/public/${encodeURIComponent(token)}`, { cache: "no-store" });
  if (!response.ok) notFound();
  const record = await response.json() as ServiceRecord;
  return <main className="min-h-screen bg-[#f4f7f8] px-5 py-10 text-[#071a2d]"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#08758a]">Your service record</p><h1 className="mt-2 text-4xl font-bold">{record.job_title}</h1><p className="mt-2 text-slate-600">Completed by {record.contractor_name} on {record.completed_on}</p>{record.service_address && <p className="text-sm text-slate-500">{record.service_address}</p>}<div className="mt-8 space-y-4"><section className="rounded-2xl bg-[#071a2d] p-6 text-white"><h2 className="text-xl font-bold">What was done</h2><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-200">{record.job_summary}</p>{record.invoice_reference && <p className="mt-4 text-sm text-slate-400">Invoice reference: {record.invoice_reference}</p>}{record.receipt_url && <a href={record.receipt_url} target="_blank" rel="noreferrer" className="mt-4 inline-block font-semibold text-cyan-300 underline">Open receipt</a>}</section>{record.warranty_summary && <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Warranty</h2><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-600">{record.warranty_summary}</p>{record.warranty_expires_on && <p className="mt-3 text-sm font-semibold">Coverage date: {record.warranty_expires_on}</p>}</section>}{record.maintenance_instructions && <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">How to look after it</h2><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-600">{record.maintenance_instructions}</p>{record.next_service_on && <p className="mt-3 font-semibold text-[#08758a]">Recommended next service: {record.next_service_on}</p>}</section>}{record.work_photo_urls.length > 0 && <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Work photos</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{record.work_photo_urls.map(url => <img key={url} src={url} alt="Contractor supplied work record" className="rounded-xl border border-slate-200" />)}</div></section>}<ServiceRecordActions token={token} /></div><footer className="mt-8 text-center text-xs text-slate-500">This private record was created by {record.contractor_name} using Pacific North Systems Never Forget.</footer></div></main>;
}
